FROM buildpack-deps:stretch



# Versions of Nginx and nginx-rtmp-module and ffmpeg
ENV NGINX_VERSION nginx-1.21.6


# Install dependencies
RUN apt-get update && \
    # apt-get install -y dialog apt-utils && \
    apt-get install -y ca-certificates openssl libssl-dev --no-install-recommends  && \
    rm -rf /var/lib/apt/lists/*

# # Set up config file
RUN mkdir -p /etc/nginx/ssl && chmod 777 /etc/nginx/ssl
COPY rankworks.conf /etc/nginx/nginx.conf


# Download and decompress Nginx
RUN mkdir -p /tmp/build/nginx && \
    cd /tmp/build/nginx && \
    wget -O ${NGINX_VERSION}.tar.gz https://nginx.org/download/${NGINX_VERSION}.tar.gz && \
    tar -zxf ${NGINX_VERSION}.tar.gz

# Build and install Nginx
# The default puts everything under /usr/local/nginx, so it's needed to change
# it explicitly. Not just for order but to have it in the PATH
RUN cd /tmp/build/nginx/${NGINX_VERSION} && \
    ./configure \
        --sbin-path=/usr/local/sbin/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --pid-path=/var/run/nginx/nginx.pid \
        --lock-path=/var/lock/nginx/nginx.lock \
        --http-log-path=/var/log/nginx/access.log \
        --http-client-body-temp-path=/tmp/nginx-client-body \
        --with-http_ssl_module \
        --with-threads \
        --with-ipv6 \
    make -j $(getconf _NPROCESSORS_ONLN) && \
    make install && \
    mkdir /var/lock/nginx && \
    rm -rf /tmp/build

# Forward logs to Docker
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

 
EXPOSE 80
EXPOSE 443




